name: Java CI

on:
  push:
    branches:    
      - v2
      - v2-unstable
      - v4
      - v4-unstable
      - v5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Upload to Bintray & CurseForge
      run: ./gradlew clean bintrayUpload curseforge
      env:
        BINTRAY_USER: shedaniel
        OSS_TOKEN: shedaniel
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        OSS_PASS: ${{ secrets.OSS_PASS }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
